### ISSUE TITLE
Enamine Data

### ISSUE THREAD

**Issue by hypefolder** [Actelion/openchemlib-hyperspace#6]
Thank you for providing this amazing tool!

Would you also be able to provide the data necessary to search in the Enamine REAL space as you described in your paper (e.g. `REAL_Space_latest_FragFp.data`)?

If not, could you please provide any information on how to prepare the space file (e.g. `REAL_Space_latest_FragFp.txt`? I have obtained the building blocks from Enamine but cannot find the reaction templates.

Thank you for your help in advance.

**Comment by thsa** [comment]
The REAL space files are not publicly available. You may contact Enamine. Alternatively, you may use DataWarrior, which provides free 2D search in the Enamine REAL Space (besides others) using the Hyperspace plugin that you can install from the Help menu.

**Comment by lithom** [comment]
The input required for the Hyperspace tool is a synthon representation of the combinatorial library 
space. This means, having just the building blocks is not sufficient to use the tool.

It is not straight-forward to create synthon spaces, even if you know the building blocks and the generic reactions (i.e. the chemical transformations that take place). Approaches as discussed in https://pubs.acs.org/doi/abs/10.1021/acs.jcim.1c01041 can be used to create synthon spaces / synthon representations from building blocks and generic descriptions of the reactions.

**Comment by hypefolder** [comment]
@thsa Thank you for your prompt response and for pointing me to the Hyperspace plugin, it's perfect for our intended use :)

@lithom Thanks for your detailed reply and for linking to the paper. In the long run we'd like to build our own synthon space, but I now see that it's not trivial and I have some reading up to do before we can get there.
