### ISSUE TITLE
Creating Hyperspace input

### ISSUE THREAD

**Issue by and-tos** [Actelion/openchemlib-hyperspace#7]
I create the input for Hyperspace with this command:

`java -jar $EBROOTHYPERSPACE/openchemlib-hyperspace-cli/target/openchemlib-hyperspace-cli.jar CREATESPACE synthons.tsv spacename FragFp 16`

But I noticed in the Readme that there is the following command:
`java -Xmx16G  com.idorsia.research.chem.hyperspace.io.SynthonSpaceParser2 /home/liphath1/hyperspace_base_2/data/REAL_Space_latest/2021-02_REAL_synthons_SMALL.txt <name_of_space_file> FragFp <number_of_threads>`

Is there a difference between the two methods?

**Comment by lithom** [comment]
Both methods should do exactly the same and should also yield exactly the same files. Did you notice any problems with one of the methods?

**Comment by and-tos** [comment]
Thanks for the info, I did not yet use the latest version. I was just curious about what the recent updates entail.
